// Guest-facing English text for data/exp.js. No prices. Photos come from exp.js (img).
// when: morning / afternoon / evening / fullday / kanazawa
// cat:  anime / make / food / walk / outdoor
window.EN = {
  "akiba":     {t:"Akihabara with an otaku guide", d:"Figures, retro games, arcades. Private for your group. I pick the shops for the anime you like.", cat:"anime", when:"afternoon", area:"Akihabara", dur:"3h 45m", start:"11:00 or 16:00", meet:"JR Akihabara Sta.", cap:"Private, up to 10", age:"5+", host:"Yuuki"},
  "leather":   {t:"Sew a small leather wallet", d:"A leather craftsman shows you how. You sew it by hand and take it home the same day. Easy for first timers.", cat:"make", when:"afternoon", area:"Nakameguro", dur:"1h 30m", start:"Weekdays, ask", meet:"7 min from Nakameguro Sta.", cap:"Small group", age:"7+", host:"Hige-chan"},
  "sandal":    {t:"Make your own leather sandals", d:"Same workshop, longer class. You build sandals to fit your own feet. A shoulder bag class is also OK.", cat:"make", when:"afternoon", area:"Nakameguro", dur:"About 3h", start:"Weekdays, ask", meet:"7 min from Nakameguro Sta.", cap:"Small group", age:"13+", host:"Hige-chan"},
  "ramen":     {t:"Make ramen noodles at a noodle factory", d:"Make your own noodles at a family noodle factory. Then cook ramen and gyoza in a home kitchen and eat!", cat:"food", when:"evening", area:"Yokohama", dur:"About 5h", start:"16:00", meet:"Kikuna Sta.", cap:"Up to 5", age:"5+", host:"Akiko"},
  "izakaya":   {t:"Izakaya hopping in Shinjuku", d:"Lanterns, yakitori and a toast. We go to a few bars where local people go. Food and drinks included.", cat:"food", when:"evening", area:"Shinjuku", dur:"About 3h", start:"17:30", meet:"Shinjuku", cap:"Up to 10", age:"10+", host:"Yoshi"},
  "coffee":    {t:"Old cafes and coffee roasters", d:"Walk from Akihabara to Jimbocho. Old kissaten and new coffee shops. You hear the story of each shop.", cat:"walk", when:"morning", area:"Akihabara to Jimbocho", dur:"3h 45m", start:"9:45 / 11:00 / 13:00 / 14:30", meet:"Akihabara", cap:"Ask", age:"2+", host:"Tomoyo"},
  "custom":    {t:"Your own Tokyo day", d:"Tell us what you like. The guide plans the day for you. Pick-up included. Good for families.", cat:"walk", when:"morning", area:"Tokyo", dur:"About 5h", start:"10:00", meet:"Pick-up in Chiyoda", cap:"Up to 6", age:"2+", host:"Ayano"},
  "boat":      {t:"Drive a boat in Tokyo Bay", d:"No license needed. You steer the boat next to the captain. See the city from the sea.", cat:"outdoor", when:"afternoon", area:"Tokyo Bay", dur:"Ask", start:"Ask", meet:"Koto", cap:"Up to 10", age:"3+", host:"Yuichi"},
  "kzsushi":   {t:"Sushi class in Kanazawa", d:"Learn to make sushi and local food at a cooking school. Then eat it. Lunch or dinner.", cat:"food", when:"kanazawa", area:"Kanazawa", dur:"2h 45m", start:"11:00 or 18:00", meet:"Cooking school in Kanazawa", cap:"From 2", age:"12+", host:"Seiji"},
  "kanazawa":  {t:"Half day in Kanazawa with a local", d:"Kenroku-en, Omicho market, the old tea house street. Tell her where you want to go. She is also a nurse.", cat:"walk", when:"kanazawa", area:"Kanazawa", dur:"5 to 6h", start:"Ask", meet:"Kanazawa", cap:"Private", age:"", host:"Yuriya"},

  "c-shibuya":    {t:"Shibuya to the river, on foot", d:"Cross the Scramble, walk 20 min to Daikanyama T-Site, end at the Meguro River cafes. All walking.", cat:"walk", when:"afternoon", area:"Shibuya, Daikanyama, Nakameguro", dur:"About 4h 15m", start:"13:00", meet:"Hachiko, Shibuya"},
  "c-kappabashi": {t:"Make fake food in Kappabashi", d:"Make your own plastic food sample, like in restaurant windows. Then walk to Senso-ji. Fun and a souvenir.", cat:"make", when:"afternoon", area:"Asakusa, Kappabashi", dur:"About 3h 30m", start:"13:30", meet:"Kappabashi"},
  "c-ginza":      {t:"Ginza stationery and old shops", d:"Itoya, a depachika food floor, a 150-year-old bakery, a rooftop garden. About 2 km, flat, no trains.", cat:"walk", when:"afternoon", area:"Ginza", dur:"About 3h 45m", start:"13:30", meet:"Itoya, Ginza"},
  "c-akiba":      {t:"Akihabara, top to bottom", d:"Big shops and small hidden ones. Retro games, a maid cafe, and Kanda Myojin shrine at the end.", cat:"anime", when:"fullday", area:"Akihabara", dur:"About 7h 30m", start:"10:00", meet:"Akihabara Sta."},
  "c-ikebukuro":  {t:"Where manga was born", d:"Morning at Tokiwa-so, the old apartment of Tezuka and friends. Afternoon in Ikebukuro: Animate, Otome Road, Pokemon Center.", cat:"anime", when:"fullday", area:"Shiinamachi, Ikebukuro", dur:"About 8h", start:"10:00", meet:"Tokiwa-so Manga Museum"},
  "c-ghibli":     {t:"Ghibli Museum and Nakano Broadway", d:"Ghibli Museum in the morning (tickets sell out months before). Old cels and comics at Nakano Broadway after.", cat:"anime", when:"fullday", area:"Mitaka, Nakano", dur:"About 7h", start:"10:00", meet:"Ghibli Museum"},
  "c-tsukiji":    {t:"Market breakfast and matcha", d:"For jet lag mornings. Breakfast at Tsukiji outer market, matcha at a tea house in Hama-rikyu. Back by lunch.", cat:"food", when:"morning", area:"Tsukiji, Hama-rikyu", dur:"About 5h", start:"7:30", meet:"From your hotel"},
  "c-meiji":      {t:"Meiji Shrine forest and the park", d:"Walk the shrine forest, then Yoyogi Park. On Sundays people play music and dance. Lunch in Omotesando.", cat:"outdoor", when:"morning", area:"Harajuku, Omotesando", dur:"About 6h", start:"9:30", meet:"From your hotel"},
  "c-ryogoku":    {t:"Old Edo and Hokusai", d:"Two museums in Ryogoku. Chanko nabe for lunch, then the sumo hall. Mostly indoors, good for rain.", cat:"walk", when:"fullday", area:"Ryogoku", dur:"About 5h 45m", start:"10:00", meet:"From your hotel"}
};
window.ORDER = ["akiba","ramen","leather","izakaya","c-kappabashi","boat","coffee","c-ghibli","sandal","c-tsukiji","custom","c-ikebukuro","c-shibuya","c-akiba","c-ginza","c-meiji","c-ryogoku","kzsushi","kanazawa"];
window.CREDIT = "Photos: tours from each host. Routes from Wikimedia Commons: Tsutaya-1 (CC BY-SA 3.0), Sampuru plastic food items (CC BY 2.0), GINZA SIX Atrium View 201912 (CC BY 4.0), Akihabara (CC BY 2.0), Bookshelves with manga (CC BY 2.0), Ghibli Museum Mitaka 08 (CC BY 2.0), Tsukiji Outer Market -02 (CC BY-SA 3.0), Traditional wedding at Meiji-jingu 2006-10-29 (CC BY-SA 2.0), The Great Wave off Kanagawa (public domain).";
