// Guest-facing English text for data/exp.js. No prices. Photos come from exp.js (img).
// when: morning / afternoon / evening / fullday / kanazawa
// cat:  anime / make / food / walk / outdoor
window.EN = {
  "akiba":     {t:"Akihabara with an otaku guide", d:"Figures, retro games, arcades. Private for your group. I pick the shops for the anime you like.", cat:"anime", when:"afternoon", area:"Akihabara", dur:"3h 45m", start:"11:00 or 16:00", meet:"JR Akihabara Sta.", cap:"Private, up to 10", age:"5+", host:"Yuuki"},
  "leather":   {t:"Sew a small leather wallet", d:"A leather craftsman shows you how. You sew it by hand and take it home the same day. Easy for first timers.", cat:"make", when:"afternoon", area:"Nakameguro", dur:"1h 30m", start:"Weekdays, ask", meet:"7 min from Nakameguro Sta.", cap:"Small group", age:"7+", host:"Hige-chan"},
  "sandal":    {t:"Make your own leather sandals", d:"Same workshop, longer class. You build sandals to fit your own feet. A shoulder bag class is also OK.", cat:"make", when:"afternoon", area:"Nakameguro", dur:"About 3h", start:"Weekdays, ask", meet:"7 min from Nakameguro Sta.", cap:"Small group", age:"13+", host:"Hige-chan"},
  "ramen":     {t:"Make ramen noodles at a noodle factory", d:"Make your own noodles at a family noodle factory. Then cook ramen and gyoza in a home kitchen and eat!", cat:"food", when:"evening", area:"Yokohama", dur:"About 5h", start:"16:00", meet:"Kikuna Sta.", cap:"Up to 5", age:"5+", host:"Akiko"},
  "izakaya":   {t:"Izakaya hopping in Shinjuku", d:"Lanterns, yakitori and a toast. We go to a few bars where local people go. Food and drinks included.", cat:"food", when:"evening", area:"Shinjuku", dur:"About 3h", start:"17:30", meet:"Shinjuku", cap:"Up to 10", age:"10+", host:"Yoshi"},
  "coffee":    {t:"Old cafes and coffee roasters", d:"Walk from Akihabara to Jimbocho. Old kissaten and new coffee shops. You hear the story of each shop.", cat:"walk", when:"morning", area:"Akihabara to Jimbocho", dur:"3h 45m", start:"9:45 / 11:00 / 13:00 / 14:30", meet:"Akihabara", cap:"Ask", age:"2+", host:"Tomoyo"},
  "custom":    {t:"Your own Tokyo day", d:"Tell us what you like. The guide plans the day for you. Pick-up included. Good for families.", cat:"walk", when:"morning", area:"Tokyo", dur:"About 5h", start:"10:00", meet:"Pick-up in Chiyoda", cap:"Up to 6", age:"2+", host:"Ayano"},
  "boat":      {t:"Drive a boat in Tokyo Bay", d:"No license needed. You steer the boat next to the captain. See the city from the sea.", cat:"outdoor", when:"afternoon", area:"Tokyo Bay", dur:"Ask", start:"Ask", meet:"Koto", cap:"Up to 10", age:"3+", host:"Yuichi"},
  "kzsushi":   {t:"Sushi class in Kanazawa", d:"Learn to make sushi and local food at a cooking school. Then eat it. Lunch or dinner.", cat:"food", when:"kanazawa", area:"Kanazawa", dur:"2h 45m", start:"11:00 or 18:00", meet:"Cooking school in Kanazawa", cap:"From 2", age:"12+", host:"Seiji"},
  "kanazawa":  {t:"Half day in Kanazawa with a local", d:"Kenroku-en, Omicho market, the old tea house street. Tell her where you want to go. She is also a nurse.", cat:"walk", when:"kanazawa", area:"Kanazawa", dur:"5 to 6h", start:"Ask", meet:"Kanazawa", cap:"Private", age:"", host:"Yuriya"},

  "c-shibuya":    {t:"Shibuya to the river, on foot", d:"Cross the Scramble, walk 20 min to Daikanyama T-Site, end at the Meguro River cafes. All walking.", cat:"walk", when:"afternoon", area:"Shibuya, Daikanyama, Nakameguro", dur:"About 4h 15m", start:"13:00", meet:"Hachiko, Shibuya"},
  "c-kappabashi": {t:"Make fake food in Kappabashi", d:"Make your own plastic food sample, like in restaurant windows. Then walk to Senso-ji. Fun and a souvenir.", cat:"make", when:"afternoon", area:"Asakusa, Kappabashi", dur:"About 3h 30m", start:"13:30", meet:"Kappabashi"},
  "c-ginza":      {t:"Ginza stationery and old shops", d:"Itoya, a depachika food floor, a 150-year-old bakery, a rooftop garden. About 2 km, flat, no trains.", cat:"walk", when:"afternoon", area:"Ginza", dur:"About 3h 45m", start:"13:30", meet:"Itoya, Ginza"},
  "c-akiba":      {t:"Akihabara, top to bottom", d:"Big shops and small hidden ones. Retro games, a maid cafe, and Kanda Myojin shrine at the end.", cat:"anime", when:"fullday", area:"Akihabara", dur:"About 7h 30m", start:"10:00", meet:"Akihabara Sta."},
  "c-ikebukuro":  {t:"Where manga was born", d:"Morning at Tokiwa-so, the old apartment of Tezuka and friends. Afternoon in Ikebukuro: Animate, Otome Road, Pokemon Center.", cat:"anime", when:"fullday", area:"Shiinamachi, Ikebukuro", dur:"About 8h", start:"10:00", meet:"Tokiwa-so Manga Museum"},
  "c-ghibli":     {t:"Ghibli Museum and Nakano Broadway", d:"Ghibli Museum in the morning (tickets sell out months before). Old cels and comics at Nakano Broadway after.", cat:"anime", when:"fullday", area:"Mitaka, Nakano", dur:"About 7h", start:"10:00", meet:"Ghibli Museum"},
  "c-tsukiji":    {t:"Market breakfast and matcha", d:"For jet lag mornings. Breakfast at Tsukiji outer market, matcha at a tea house in Hama-rikyu. Back by lunch.", cat:"food", when:"morning", area:"Tsukiji, Hama-rikyu", dur:"About 5h", start:"7:30", meet:"From your hotel"},
  "c-meiji":      {t:"Meiji Shrine forest and the park", d:"Walk the shrine forest, then Yoyogi Park. On Sundays people play music and dance. Lunch in Omotesando.", cat:"outdoor", when:"morning", area:"Harajuku, Omotesando", dur:"About 6h", start:"9:30", meet:"From your hotel"},
  "c-ryogoku":    {t:"Old Edo and Hokusai", d:"Two museums in Ryogoku. Chanko nabe for lunch, then the sumo hall. Mostly indoors, good for rain.", cat:"walk", when:"fullday", area:"Ryogoku", dur:"About 5h 45m", start:"10:00", meet:"From your hotel"}
};
window.ORDER = ["akiba","ramen","leather","izakaya","c-kappabashi","boat","coffee","c-ghibli","sandal","c-tsukiji","custom","c-ikebukuro","c-shibuya","c-akiba","c-ginza","c-meiji","c-ryogoku","kzsushi","kanazawa"];
window.CREDIT = "Photos: tours from each host. Routes from Wikimedia Commons: Tsutaya-1 (CC BY-SA 3.0), Sampuru plastic food items (CC BY 2.0), GINZA SIX Atrium View 201912 (CC BY 4.0), Akihabara (CC BY 2.0), Bookshelves with manga (CC BY 2.0), Ghibli Museum Mitaka 08 (CC BY 2.0), Tsukiji Outer Market -02 (CC BY-SA 3.0), Traditional wedding at Meiji-jingu 2006-10-29 (CC BY-SA 2.0), The Great Wave off Kanagawa (public domain).";

// 5 photos per experience: [file in img/g/, caption]. First one is the card photo.
window.GAL = {
  "akiba":   [["akiba-1","Retro game arcade"],["akiba-2","Plush toy hunting"],["akiba-3","Anime shirts and goods"],["akiba-4","Arcade games"],["akiba-5","Kanda Myojin shrine"]],
  "leather": [["leather-1","Sewing with the craftsman"],["leather-2","Hige-chan, your teacher"],["leather-3","Stitch it by hand"],["leather-4","Pieces and tools"],["leather-5","Almost done"]],
  "sandal":  [["sandal-1","In the workshop"],["sandal-2","He shows you each step"],["sandal-3","Your sandals"],["sandal-4","Fit them to your feet"],["sandal-5","Pick a style"]],
  "ramen":   [["ramen-1","Making noodles at the factory"],["ramen-2","Fresh noodles"],["ramen-3","Ramen time at home"],["ramen-4","Gyoza you made"],["ramen-5","Cooking with Akiko"]],
  "izakaya": [["izakaya-1","Yoshi tells the story"],["izakaya-2","Old alley in Shinjuku"],["izakaya-3","Skewers and drinks"],["izakaya-4","A local izakaya"],["izakaya-5","Shinjuku at night"]],
  "coffee":  [["coffee-1","Coffee to go"],["coffee-2","Walking with Tomoyo"],["coffee-3","An old kissaten"],["coffee-4","Old wooden building"],["coffee-5","A new coffee bar"]],
  "custom":  [["custom-1","A family day out"],["custom-2","Meiji Shrine forest"],["custom-3","The big torii gate"],["custom-4","Matcha break"],["custom-5","Wash your hands at the shrine"]],
  "boat":    [["boat-1","Relax on the deck"],["boat-2","Steer the boat"],["boat-3","Rainbow Bridge"],["boat-4","Wave to the city"],["boat-5","Under the bridge"]],
  "kzsushi": [["kzsushi-1","Cooking class"],["kzsushi-2","Have fun with the chef"],["kzsushi-3","Your lunch set"],["kzsushi-4","Nigiri sushi"],["kzsushi-5","Your chef hats"]],
  "kanazawa":[["kanazawa-1","Walking the town"],["kanazawa-2","Higashi Chaya tea street"],["kanazawa-3","Kenroku-en garden"],["kanazawa-4","Tea break"],["kanazawa-5","Kanazawa Station gate"]]
};
window.TALL = ["akiba","coffee","leather","sandal"]; // card photo is portrait

// Routes: photos from Wikimedia Commons
window.GAL["c-shibuya"] = [["c-shibuya-1", "Shibuya Scramble"], ["c-shibuya-2", "Shibuya from above"], ["c-shibuya-3", "Daikanyama T-Site"], ["c-shibuya-4", "Meguro River"], ["c-shibuya-5", "Starbucks Reserve Roastery"]];
window.GAL["c-kappabashi"] = [["c-kappabashi-1", "Plastic food samples"], ["c-kappabashi-2", "Fake food in a shop window"], ["c-kappabashi-3", "Kappabashi kitchen street"], ["c-kappabashi-4", "Nakamise to Senso-ji"], ["c-kappabashi-5", "Kaminarimon gate"]];
window.GAL["c-ginza"] = [["c-ginza-1", "Walking in Ginza"], ["c-ginza-2", "Mitsukoshi department store"], ["c-ginza-3", "Anpan from Kimuraya"], ["c-ginza-4", "GINZA SIX"]];
window.GAL["c-akiba"] = [["c-akiba-1", "Akihabara main street"], ["c-akiba-2", "Retro games at Super Potato"], ["c-akiba-3", "Maid cafe street"], ["c-akiba-4", "Shops at night"], ["c-akiba-5", "Kanda Myojin shrine"]];
window.GAL["c-ikebukuro"] = [["c-ikebukuro-1", "Manga everywhere"], ["c-ikebukuro-2", "Tokiwa-so Manga Museum"], ["c-ikebukuro-3", "Animate Ikebukuro"], ["c-ikebukuro-4", "Pokemon Center Mega Tokyo"]];
window.GAL["c-ghibli"] = [["c-ghibli-1", "Robot soldier on the museum roof"], ["c-ghibli-2", "Roof garden at the Ghibli Museum"], ["c-ghibli-3", "Ghibli bus from Mitaka Station"], ["c-ghibli-4", "Boats in Inokashira Park"], ["c-ghibli-5", "Inside Nakano Broadway"]];
window.GAL["c-tsukiji"] = [["c-tsukiji-1", "Tsukiji outer market"], ["c-tsukiji-2", "Fresh tamagoyaki"], ["c-tsukiji-3", "Seafood stalls"], ["c-tsukiji-4", "Hama-rikyu garden"], ["c-tsukiji-5", "Tea house on the pond"]];
window.GAL["c-meiji"] = [["c-meiji-1", "A wedding at Meiji Shrine"], ["c-meiji-2", "Big torii in the forest"], ["c-meiji-3", "Sake barrels"], ["c-meiji-4", "Omotesando"]];
window.GAL["c-ryogoku"] = [["c-ryogoku-1", "Hokusai's Great Wave"], ["c-ryogoku-2", "Sumida Hokusai Museum"], ["c-ryogoku-3", "Edo-Tokyo Museum"], ["c-ryogoku-4", "Chanko nabe for lunch"], ["c-ryogoku-5", "Kyu-Yasuda Garden"]];
window.TALL.push(...["c-ikebukuro", "c-ghibli"]);
window.CREDIT += " Also: " + "Tokyo Shibuya Scramble Crossing 2018-10-09 by Benh LIEU SONG (Flickr) (CC BY-SA 2.0); Shibuya Crossing, Aerial by David Kernan (CC BY 4.0); Daikanyama T-SITE 2016-04-04 by Jonathan Lin (CC BY-SA 2.0); Walk along Meguro river near Nakameguro 8 by Syced (CC0); Starbucks-Reserve-Roastery-Tokyo-2019-07-18 by 編集中 (CC BY-SA 4.0); Food samples 1 by Lombroso (Public domain); Cream and red coffee cup-shaped balconies, Niimi Tableware, Kappabashi Dougu Street, Tokyo, Japan by Basile Morin (CC BY-SA 4.0); The Kaminarimon at Asakusa; November 2008 by MIKI Yoshihito from Sapporo City,Hokkaido., JAPAN (CC BY 2.0); Kaminarimon (outer gate), Sensoji Temple, Akakusa, Tokyo by Daderot (Public domain); Ginza Mitsukoshi-2 by 江戸村のとくぞう (CC BY-SA 4.0); Ginza Mitsukoshi-1 by 江戸村のとくぞう (CC BY-SA 4.0); Ginza-Kimuraya-Sakura-Anpan---2023-11-28 001 by RuinDig/Yuki Uchida (CC BY 4.0); Super Potato in Akihabara (4066556528) by JoshBerglund19 from United States (CC BY 2.0); Maid Café promotion @ Akihabara by Guilhem Vellut (CC BY 2.0); Akihabara Radio Kaikan, 2010-03-06 by street viewer (CC BY 2.0); Saimu-sho and Kagura-den of Kanda-Myojin, Soto-Kanda, Chiyoda, Tokyo, Japan, 2024 May by Ximonic (Simo Räsänen) (CC BY-SA 4.0); Tokiwaso-Manga-Museum by Tokyo-Good (CC BY-SA 4.0); Animate Ikebukuro 20120613 2 by Dick Thomas Johnson (CC BY 2.0); Mega Tokyo Pokémon Center 1 by Maplestrip (CC BY 3.0); Ghibli Museum Mitaka 11 (2384482761) by Stéphane Gallay from Laconnex, Switzerland (CC BY 2.0); Mitaka City Bus 278 and Ghibli Museum stop board 20050218 by Nicholas Wang (CC BY-SA 2.0); Once Upon A Time (110276553) by Susanna Zema (CC BY 3.0); Nakano Broadway 2021130 ④ by 番記者 (CC BY-SA 4.0); Tsukiji Market 2017 (38052266396) by Kent Wang from London, United Kingdom (CC BY-SA 2.0); Tsukiji Outer Market 2 by Aw1805 (CC BY-SA 3.0); Hama-rikyu garden against the Tokyo skyline (53620865036) by Winniepix (CC BY 2.0); Nakajima-no-ochaya-20091017-RM-141803 by Reinhold Möller Ermell (CC BY-SA 4.0); Meiji-jingu Torii 1 by Zairon (CC BY-SA 4.0); Meiji Jingu sake barrels closeup 2016-12-04 by KFP (CC BY 4.0); Street crowd reflecting in the polyhedral mirrors of the station Tokyu Plaza Omotesando, Harajuku, Tokyo, Japan by Basile Morin (CC BY-SA 4.0); 2018 Sumida Hokusai Museum 2 by Kakidai (CC BY-SA 4.0); Edo-Tokyo Museum by Wiiii (CC BY-SA 3.0); Chankonabe by George N (CC BY 2.0); Kyu Yasuda teien 01 by bethom33 (CC BY-SA 2.0)" + ".";
